// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaz3KR8FUSzGaS3vmzYxj_ncS2jOkcKls',
    appId: '1:792039400646:web:6cbef0a912e44599ea63c7',
    messagingSenderId: '792039400646',
    projectId: 'chat-app-e1bf7',
    authDomain: 'chat-app-e1bf7.firebaseapp.com',
    storageBucket: 'chat-app-e1bf7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCatPWhx1S71IGxLcOaMVZ7enW2ZG-lXf8',
    appId: '1:792039400646:android:8851d499194e250eea63c7',
    messagingSenderId: '792039400646',
    projectId: 'chat-app-e1bf7',
    storageBucket: 'chat-app-e1bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-eUMHNzTZDcAxF05TpiH4uMEdTE7wBjU',
    appId: '1:792039400646:ios:adb71d8a1023a70fea63c7',
    messagingSenderId: '792039400646',
    projectId: 'chat-app-e1bf7',
    storageBucket: 'chat-app-e1bf7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-eUMHNzTZDcAxF05TpiH4uMEdTE7wBjU',
    appId: '1:792039400646:ios:adb71d8a1023a70fea63c7',
    messagingSenderId: '792039400646',
    projectId: 'chat-app-e1bf7',
    storageBucket: 'chat-app-e1bf7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaz3KR8FUSzGaS3vmzYxj_ncS2jOkcKls',
    appId: '1:792039400646:web:89acfd475a2d2e34ea63c7',
    messagingSenderId: '792039400646',
    projectId: 'chat-app-e1bf7',
    authDomain: 'chat-app-e1bf7.firebaseapp.com',
    storageBucket: 'chat-app-e1bf7.firebasestorage.app',
  );
}
